services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clicker-empire-database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - clicker-empire-sql-data:/var/opt/mssql

volumes:
  clicker-empire-sql-data:
